import jarvisImg from "@/assets/jarvis.png.asset.json";
import sageImg from "@/assets/sage.png.asset.json";
import spotlightImg from "@/assets/spotlight.png.asset.json";
import drawerImg from "@/assets/drawer.png.asset.json";

export interface Project {
  slug: string;
  name: string;
  tagline: string;
  tags: string[];
  duration: string;
  category: string;
  role: string;
  tools: string;
  image: string;
  cardBlurb: string;
  overview: string;
  problem: string;
  solution: string;
  features: string[];
  outcome: string;
  learning: string;
  whatsNext: string[];
  impact: { value: string; label: string }[];
  livePreview?: string;
}

export const projects: Project[] = [
  {
    slug: "jarvis-command-centre",
    name: "JARVIS Command Centre",
    tagline: "Project OS · Execution Management · Smart Alerts",
    tags: ["Project OS", "Execution", "Smart Alerts"],
    duration: "Jan 2024 – Mar 2024",
    category: "Productivity, Project Management",
    role: "Product Manager · Product Designer · Workflow Architect · AI-Assisted Builder",
    tools: "AI-assisted Development, Data Visualization, UX Design",
    image: jarvisImg.url,
    cardBlurb:
      "Central hub for projects, priorities, productivity and smart alerts. A personal command centre that gives a real-time view of projects, tasks, timelines and productivity.",
    overview:
      "Most productivity systems are built for one context — work, or personal, or projects. Real life doesn't work that way. JARVIS Command Centre is a personal operating system built not to track tasks, but to manage execution across every context simultaneously.",
    problem:
      "I was running 28 concurrent workstreams — professional delivery, Healthire, Opez, certifications, personal milestones. Nothing talked to each other. Priority decisions were being made on gut feel because I had no single view of what was actually in flight, what was stalled, and what was about to fall off. The cost wasn't missed tasks — it was invisible cognitive load.",
    solution:
      "JARVIS is a unified command centre that pulls every project, every priority, and every active workstream into a single interface. Not a task list. Not a Kanban board. A command centre — built for someone who needs operational visibility, not productivity theatre.",
    features: [
      "Project Portfolio Dashboard — all 28 projects visible in one view with status, priority, progress %, and last updated timestamp",
      "Priority Matrix — High / Medium / Low / None distribution at a glance",
      "Timeline Overview — Due Today, Due Soon, Upcoming, Future, No Date buckets",
      "Smart Alerts Engine — surfaces overdue projects, missing deadlines, stalled work, and pending actions automatically",
      "Productivity Scoring — weekly execution score based on tasks completed, projects updated, and automations run",
      "AI Command Bar — natural language queries to surface project state and next actions",
    ],
    outcome:
      "JARVIS replaced 5 fragmented tools with one. More importantly, it replaced the mental overhead of holding the full picture in my head with a system that holds it for me.",
    learning:
      "Dashboards are only valuable if they change what you do next. The breakthrough came when I stopped asking ‘what should I display?’ and started asking ‘what does someone need to see to take the right action?’",
    whatsNext: [
      "AI-assisted priority recommendations based on deadlines and workload",
      "Cross-project dependency mapping",
      "Weekly execution review auto-generated by the AI layer",
      "Calendar and communication tool integration",
      "Team mode — same logic applied to a delivery team",
    ],
    impact: [
      { value: "28+", label: "Projects Managed" },
      { value: "112+", label: "Tasks Completed" },
      { value: "78%", label: "Productivity Score" },
      { value: "15%", label: "Increase in Efficiency" },
    ],
  },
  {
    slug: "sage-scheduler",
    name: "Sage Scheduler",
    tagline: "AI Scheduling · Outlook Integration · Claude API",
    tags: ["Workflow Automation"],
    duration: "Mar 2024 – May 2024",
    category: "Workflow Automation",
    role: "Product Manager · Workflow Designer · UX Designer · AI-Assisted Builder",
    tools: "Claude API, Microsoft Graph, AI-assisted Development",
    image: sageImg.url,
    cardBlurb:
      "AI-powered scheduling workspace that understands emails, checks availability and drafts meeting invites.",
    overview:
      "Scheduling a PS kickoff call is never just scheduling a kickoff call. It's reading a customer email, interpreting it, checking a consultant's calendar, drafting a reply, sending an invite, and following up. Sage Scheduler was built to handle all of it.",
    problem:
      "Consultants lose hours every week to scheduling coordination. The cycle of reading vague emails, checking calendars, drafting replies, and resolving conflicts repeats across every case. Every step is manual, sequential, and completely automatable.",
    solution:
      "Sage Scheduler collapses the entire scheduling workflow into three steps: drop in the customer's email, configure the consultant and window, and get available slots, a meeting invite, and a reply email draft — ready to send. The consultant stays in control of the final decision.",
    features: [
      "Email Intake — drop or paste customer emails; AI extracts scheduling intent",
      "AI Interpretation Layer — Claude API reads conversational language",
      "Live Calendar Availability — Microsoft Graph fetches real free/busy slots from Outlook",
      "Scheduling Window Configuration — standard and custom windows per case",
      "Meeting Invite Generation — auto-generated from confirmed slot",
      "Reply Email Draft — customer-facing response drafted automatically",
      "Correction Chat — quick interface for customer follow-ups",
    ],
    outcome:
      "What previously took 3–4 email exchanges over 2–3 days now takes minutes. The cognitive load of scheduling coordination is handled by the system.",
    learning:
      "The instinct when building AI tools is to make them fully autonomous. The best version of Sage Scheduler is one where AI does the heavy lifting but the consultant makes the final call. Users don't want to be removed from the process — they want the friction removed from the process.",
    whatsNext: [
      "Salesforce case integration",
      "Overbooking detection and workload balancing",
      "SLA-aware scheduling",
      "Automated follow-up sequences",
      "Team scheduling view for delivery managers",
    ],
    impact: [
      { value: "3–4", label: "Emails Replaced" },
      { value: "2–3 days", label: "Cycle → Minutes" },
      { value: "Live", label: "Outlook Sync" },
      { value: "1-Click", label: "Invite + Draft" },
    ],
  },
  {
    slug: "opez-spotlight",
    name: "Opez Spotlight",
    tagline: "PS Delivery · SLA Compliance · Excel Ingestion",
    tags: ["Analytics", "Reporting"],
    duration: "Feb 2024 – Apr 2024",
    category: "Analytics, Reporting",
    role: "Product Manager · Business Analyst · UX Designer · AI-Assisted Builder",
    tools: "Data Visualization, Excel Ingestion, AI-assisted Development",
    image: spotlightImg.url,
    cardBlurb:
      "Customer onboarding SLA and KPI tracker that provides real-time insights and performance visibility.",
    overview:
      "Every PS team has the same problem: SLA data exists, but getting to it requires someone to pull a report, format a spreadsheet, and send it around — by which point it's already out of date. Opez Spotlight makes that problem disappear.",
    problem:
      "SLA breaches rarely surprise anyone in hindsight. The signals were always there. By the time a manager sees it in a report, the breach has already happened. The gap isn't data — it's visibility.",
    solution:
      "Opez Spotlight turns a raw Excel onboarding file into a live compliance dashboard in one upload. It calculates SLA performance, flags breaches with days-over-SLA detail, tracks per-consultant performance, and surfaces cases needing immediate attention.",
    features: [
      "One-Click Data Upload — Excel ingestion, no formatting requirements",
      "Kickoff SLA Tracking — 15 business day target",
      "Scheduling SLA Tracking — 3 business day target",
      "KPI Summary Cards — Kickoff %, Scheduling %, Team target achievement",
      "Visual SLA Breakdown — donut charts for Met vs. Missed",
      "Per-Consultant Performance — bar chart against 10-call target",
      "Cases Requiring Attention — sorted exception list with days over SLA",
    ],
    outcome:
      "Weekly reporting cycles compressed to under a minute. The output is actionable: managers see the breach, see who owns it, and act immediately.",
    learning:
      "The temptation in data tools is to add more charts. The most important design decision was the Cases Requiring Attention table — a deliberately simple prioritised list. Build for the decision, not the data.",
    whatsNext: [
      "Direct Salesforce and Jira integration",
      "Automated SLA breach alerts to Slack or email",
      "Trend analysis over time",
      "Consultant workload view mapped to case volume",
      "Predictive risk scoring",
    ],
    impact: [
      { value: "1 Upload", label: "To Dashboard" },
      { value: "<60s", label: "Weekly Report" },
      { value: "100%", label: "SLA Visibility" },
      { value: "Real-time", label: "Exception List" },
    ],
  },
  {
    slug: "drawer",
    name: "Drawer",
    tagline: "Workspace Launcher · Universal Search · Keyboard-First",
    tags: ["Productivity"],
    duration: "Jan 2024 – Feb 2024",
    category: "Productivity",
    role: "Product Manager · Product Designer · UX Designer · AI-Assisted Builder",
    tools: "AI-assisted Development, UX Design",
    image: drawerImg.url,
    cardBlurb:
      "Personal workspace to organize apps, websites, documents and tools in one place for quick access.",
    overview:
      "Modern professionals use more tools than ever. Drawer is the fix — a unified workspace launcher that puts every app, website, file, and tool one keystroke away. Think WebCatalog, built around how operators actually work.",
    problem:
      "Running tools across two ventures and a full-time job meant constant context switching. The friction wasn't dramatic — it was constant and invisible, small enough to ignore, significant enough to compound into real lost time.",
    solution:
      "Drawer organises every resource — apps, websites, documents, AI tools, workspaces — into a single command centre with keyboard-first access and context-based organisation.",
    features: [
      "Workspace-Based Organisation — resources grouped by context",
      "Universal Search (Ctrl+K) — across apps, websites, files, workspaces",
      "Application Launcher — launch local desktop apps from Drawer",
      "Website Launcher — open frequently used web tools instantly",
      "Document Management — access project documents without file systems",
      "Favourites & Pinning — critical resources permanently top-of-view",
      "Frequency Intelligence — surfaces most-used tools automatically",
    ],
    outcome:
      "Context switching went from a constant friction point to a non-issue. The right tool is always one shortcut away.",
    learning:
      "People don't lose time to the tools they use. They lose time to finding them. Every feature exists to answer the same question faster: where is the thing I need right now?",
    whatsNext: [
      "AI-powered resource recommendations",
      "Browser extension for adding websites directly",
      "Cross-workspace search with context-aware filtering",
      "Smart tagging and auto-categorisation",
      "Team workspaces for shared resource collections",
    ],
    impact: [
      { value: "10+", label: "Tools Unified" },
      { value: "1 Key", label: "To Anything" },
      { value: "Ctrl+K", label: "Universal Search" },
      { value: "0", label: "Context Switching Cost" },
    ],
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
